namespace CybersecurityChatbot.Data
{
    // Stores all chatbot keyword-response mappings using dictionaries.
    public static class ResponseBank
    {
        // Dictionary: keyword > response
        public static readonly Dictionary<string, string> KeywordResponses = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            // Passwords & Authentication 
            { "Password", "Use strong passwords with at least 12 characters, mixing uppercase, lowercase, numbers, and symbols. Never reuse passwords across different sites." },
            { "Passphrase", "A passphrase is a sequence of random words used as a password (e.g., 'BlueSky!River#42'). They are long, memorable, and hard to crack." },
            { "Password manager", "A password manager securely stores and generates unique passwords for all your accounts. Popular options include Bitwarden, LastPass, and 1Password." },
            { "Weak Password", "Weak passwords like '123456' or 'password' are cracked in seconds. Always use a mix of characters and avoid personal info like birthdays or names." },
            { "2FA", "Two-Factor Authentication (2FA) adds an extra verification step when logging in. Enable it wherever possible — it dramatically reduces account takeover risk." },
            { "Two Factor", "Two-Factor Authentication requires both your password and a second form of verification, such as an SMS code or authenticator app. Always enable it." },
            { "Multi Factor", "Multi-Factor Authentication (MFA) combines multiple verification methods. The more factors required, the harder it is for attackers to gain access." },
            { "Biometric", "Biometric authentication uses fingerprints, face recognition, or iris scans. While convenient, ensure your device also has a strong PIN as a backup." },
            { "OTP", "One-Time Passwords (OTP) are temporary codes sent via SMS or generated by apps like Google Authenticator. They expire quickly, making them hard to reuse." },
            { "Authentication", "Authentication verifies your identity before granting access. Use strong, unique passwords combined with 2FA for the best protection." },

            // Threats & Attacks 
            { "Phishing", "Phishing attacks trick you into revealing sensitive info via fake emails or websites. Always verify the sender's address and never click suspicious links." },
            { "Spear Phishing", "Spear phishing is a targeted phishing attack aimed at a specific person or organisation. These attacks use personal details to appear more convincing." },
            { "Smishing", "Smishing is phishing via SMS text messages. Scammers send fake texts claiming to be banks or delivery services. Never click links in unexpected texts." },
            { "Vishing", "Vishing (voice phishing) uses phone calls to trick victims into revealing personal data. Hang up and call back using the official number if you're suspicious." },
            { "Malware", "Malware is malicious software designed to harm your system. Keep your antivirus updated and avoid downloading files or attachments from unknown sources." },
            { "Ransomware", "Ransomware encrypts your files and demands payment to restore them. Back up your data regularly and never pay the ransom — it does not guarantee recovery." },
            { "Spyware", "Spyware secretly monitors your activity and sends data to attackers. Avoid downloading apps from untrusted sources and run regular antivirus scans." },
            { "Adware", "Adware displays unwanted ads and can slow your device. It may also track your browsing habits. Remove it with a reputable anti-malware tool." },
            { "Trojan", "A Trojan disguises itself as legitimate software to trick you into installing it. Only download software from official, trusted sources." },
            { "Worm", "A computer worm self-replicates across networks without user interaction. Keep your OS and software updated to patch vulnerabilities worms exploit." },
            { "Virus", "A computer virus attaches itself to legitimate files and spreads when those files are shared. Use antivirus software and scan files before opening." },
            { "Keylogger", "A keylogger records everything you type, including passwords. Use antivirus software, avoid suspicious downloads, and use on-screen keyboards for sensitive input." },
            { "Rootkit", "A rootkit hides deep in your system, giving attackers persistent access. They are hard to detect — use trusted security tools and keep your OS updated." },
            { "Botnet", "A botnet is a network of infected computers controlled by an attacker to send spam or launch attacks. Keep your device secure to avoid becoming part of one." },
            { "DDoS", "A DDoS (Distributed Denial of Service) attack floods a server with traffic to take it offline. Organisations use rate limiting and CDNs to mitigate these attacks." },
            { "Man in the Middle", "A Man-in-the-Middle (MitM) attack intercepts communication between two parties. Always use HTTPS and avoid public Wi-Fi without a VPN." },
            { "SQL Injection", "SQL Injection attacks insert malicious code into database queries. Developers must use parameterised queries and input validation to prevent this." },
            { "Cross Site Scripting", "Cross-Site Scripting (XSS) injects malicious scripts into websites. Always keep your browser updated and avoid clicking links from untrusted sources." },
            { "Zero Day", "A zero-day vulnerability is a flaw unknown to the software vendor. Update your software promptly — patches often address these before attackers can exploit them widely." },
            { "Brute Force", "A brute force attack tries every possible password combination. Use long, complex passwords and enable account lockout policies to defend against this." },
            { "Social Engineering", "Social engineering manipulates people into revealing confidential info. Be cautious of unsolicited calls, emails, or messages requesting sensitive data." },
            { "Pretexting", "Pretexting involves creating a fabricated scenario to manipulate victims into revealing info (e.g., pretending to be IT support). Always verify identities." },
            { "Baiting", "Baiting lures victims with something enticing, like a free USB drive left in a public place. Never plug in unknown devices into your computer." },
            { "Tailgating", "Tailgating (piggybacking) is when an unauthorised person follows an authorised person into a restricted area. Always challenge unfamiliar faces in secure zones." },

            // Network & Infrastructure Security 
            { "Firewall", "A firewall monitors and controls incoming/outgoing network traffic based on security rules. Always keep your firewall enabled for an extra layer of protection." },
            { "VPN", "A VPN (Virtual Private Network) encrypts your internet connection, hiding your activity from hackers and ISPs. Always use one on public Wi-Fi networks." },
            { "WiFi", "Public Wi-Fi is often unsecured and vulnerable to eavesdropping. Avoid accessing sensitive accounts on public networks, or use a VPN to encrypt your traffic." },
            { "Router", "Your home router is the gateway to your network. Change the default admin password, enable WPA3 encryption, and keep the firmware updated." },
            { "DNS", "DNS translates domain names into IP addresses. Use secure DNS providers (like Cloudflare 1.1.1.1) to prevent DNS hijacking and improve privacy." },
            { "Proxy", "A proxy server acts as an intermediary between your device and the internet. While it can mask your IP, a VPN offers stronger encryption and security." },
            { "Network segmentation", "Network segmentation divides a network into smaller zones to limit the spread of attacks. It is a key practice in securing corporate environments." },
            { "Intrusion Detection", "An Intrusion Detection System (IDS) monitors network traffic for suspicious activity and alerts administrators. It is essential for enterprise security." },
            { "Port Scanning", "Port scanning probes a network for open ports that could be exploited. Close unused ports on your router and firewall to reduce your attack surface." },

            // Data & Privacy 
            { "Encryption", "Encryption converts data into a coded format so only authorised users can read it. Always use encrypted connections (HTTPS) and encrypt sensitive files." },
            { "HTTPS", "HTTPS encrypts data between your browser and a website. Always check for the padlock icon in the address bar before entering any personal information." },
            { "Data Breach", "A data breach exposes sensitive information. If you are affected, change your passwords immediately, enable 2FA, and monitor accounts for suspicious activity." },
            { "Privacy", "Protect your privacy by reviewing app permissions, using private browsing, avoiding oversharing on social media, and reading privacy policies carefully." },
            { "GDPR", "GDPR (General Data Protection Regulation) is a European law protecting personal data. Organisations must handle your data lawfully, transparently, and securely." },
            { "POPIA", "POPIA (Protection of Personal Information Act) is South Africa's data protection law. It requires organisations to handle personal information responsibly and securely." },
            { "Data Privacy", "Data privacy means controlling who can access your personal information. Use strong privacy settings on social media and limit what you share online." },
            { "Identity Theft", "Identity theft occurs when someone steals your personal info to commit fraud. Monitor your credit reports, use strong passwords, and enable 2FA on all accounts." },
            { "Cookies", "Browser cookies track your online activity. Regularly clear cookies, use private browsing, and review cookie consent settings on websites you visit." },
            { "Metadata", "Metadata is hidden data embedded in files (e.g., GPS location in photos). Strip metadata from files before sharing them publicly to protect your privacy." },

            // Devices & Software 
            { "Antivirus", "Antivirus software detects and removes malicious programs. Keep it updated and run regular scans — real-time protection is your first line of defence." },
            { "Update", "Software updates patch security vulnerabilities. Always install updates promptly — outdated software is one of the most exploited attack vectors." },
            { "Patch", "Security patches fix known vulnerabilities in software. Enable automatic updates to ensure you receive patches as soon as they are released." },
            { "Backup", "Regular backups protect your data from ransomware, hardware failure, or accidental deletion. Follow the 3-2-1 rule: 3 copies, 2 media types, 1 offsite." },
            { "Mobile Security", "Secure your mobile device with a strong PIN or biometric lock, keep apps updated, only install apps from official stores, and avoid jailbreaking." },
            { "USB", "Unknown USB drives can contain malware designed to auto-run when plugged in. Never use a USB drive you found or received unexpectedly." },
            { "Cloud Security", "When using cloud storage, enable 2FA, use strong passwords, review sharing permissions, and encrypt sensitive files before uploading them." },
            { "IoT", "IoT (Internet of Things) devices like smart TVs and cameras are often poorly secured. Change default passwords, update firmware, and segment them on a separate network." },
            { "Operating System", "Your operating system is the foundation of your device's security. Keep it updated, use a standard user account for daily use, and enable full-disk encryption." },
            { "Browser Security", "Keep your browser updated, use trusted extensions only, enable pop-up blocking, and avoid saving passwords in the browser — use a password manager instead." },

            // Workplace & General Awareness
            { "Insider Threat", "Insider threats come from employees or contractors who misuse their access. Organisations should enforce least-privilege access and monitor unusual behaviour." },
            { "Least Privilege", "The principle of least privilege means users only get the access they need to do their job. This limits damage if an account is compromised." },
            { "Incident Response", "An incident response plan defines steps to take when a security breach occurs. Organisations should have one ready and test it regularly." },
            { "Penetration Testing", "Penetration testing (ethical hacking) simulates attacks on systems to find vulnerabilities before real attackers do. It is a key part of proactive security." },
            { "Cyber Hygiene", "Cyber hygiene refers to regular security habits like updating software, using strong passwords, and being cautious online — just like brushing your teeth daily." },
            { "Security Awareness", "Security awareness training educates users about threats and safe practices. Humans are often the weakest link — knowledge is your best defence." },
            { "Dark Web", "The dark web is a part of the internet not indexed by search engines, often used for illegal activity. Your stolen data may be sold there after a breach." },
            { "Hacker", "Hackers range from ethical (white hat) professionals who improve security, to malicious (black hat) criminals. Understanding their methods helps you stay protected." },
            { "Cybersecurity", "Cybersecurity is the practice of protecting systems, networks, and data from digital attacks. It involves technology, processes, and people working together." },
            { "Safe Browsing", "Practice safe browsing by avoiding suspicious websites, not clicking unknown links, keeping your browser updated, and using a reputable ad blocker." },
        };

        // Dictionary: conversational phrase > response
        public static readonly Dictionary<string, string> ConversationalResponses = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "How are you", "I'm doing great, thanks for asking! I'm always ready to help you stay safe online. What would you like to know about cybersecurity today?" },
            { "How are you doing", "I'm functioning perfectly and ready to help! Cybersecurity never sleeps, and neither do I. What can I assist you with?" },
            { "How do you feel", "As a chatbot I don't have feelings, but I'm fully operational and excited to help you learn about cybersecurity! What topic interests you?" },
            { "Are you okay", "I'm doing well, thank you! I'm here and ready to answer your cybersecurity questions whenever you are." },
            { "Hello", "Hello! Great to hear from you. Ask me anything about cybersecurity — type 'topics' to see what I know, or just dive right in!" },
            { "Hi", "Hi there! I'm your Cybersecurity Awareness Assistant. How can I help keep you safer online today?" },
            { "Hey", "Hey! Ready to talk cybersecurity? Ask me about passwords, phishing, malware, privacy, and much more." },
            { "Good morning", "Good morning! Starting your day with a cybersecurity check-in — smart thinking. What would you like to learn today?" },
            { "Good afternoon", "Good afternoon! Hope your day is going well. How can I help you stay cyber-safe today?" },
            { "Good evening", "Good evening! Whether you're winding down or just getting started, I'm here to answer your cybersecurity questions." },
            { "What is your purpose", "My purpose is to raise cybersecurity awareness! I can answer questions about online threats, safe practices, passwords, privacy, and much more. Type 'topics' to see everything I cover." },
            { "What's your purpose",  "My purpose is to educate and empower you with cybersecurity knowledge. I cover 65+ topics including phishing, malware, encryption, privacy laws, and more!" },
            { "Why do you exist", "I exist to help people like you stay safe in the digital world. Cyber threats are growing every day — knowledge is your best defence, and that's where I come in!" },
            { "What do you do", "I'm a Cybersecurity Awareness Chatbot! I answer questions about online threats, manage your cybersecurity tasks, quiz you, and show an activity log. Type 'help' for all commands." },
            { "Who are you", "I'm your Cybersecurity Awareness Assistant — a chatbot built in C# to help you understand and navigate the world of cybersecurity. Ask me anything!" },
            { "What are you", "I'm a C# WinForms chatbot designed to teach cybersecurity awareness. I know about 65+ topics and can manage your tasks, run quizzes, and more. Type 'help' to explore!" },
            { "Tell me about yourself", "I'm a Cybersecurity Awareness Chatbot built with C# and .NET 8. I use dictionary-based NLP to understand your questions and help you stay safe online. Type 'topics' to see what I know!" },
            { "Your name", "I'm the Cybersecurity Awareness Chatbot — you can just call me CyberBot! How can I help you today?" },
            { "What can i ask", "Great question! You can ask me about: passwords, phishing, malware, ransomware, VPNs, firewalls, 2FA, encryption, data breaches, privacy laws, and more. Type 'topics' for the full list!" },
            { "What can you do",  "I can: answer 65+ cybersecurity questions, manage tasks (type 'tasks'), show an activity log (type 'log'), run a quiz (type 'quiz'), and give security tips. Type 'help' for all commands!" },
            { "What can you help with", "I can help you understand cybersecurity topics like phishing, malware, passwords, VPNs, privacy, and more. I can also manage your tasks and quiz your knowledge! Type 'topics' to see everything." },
            { "Thank you", "You're welcome! Stay safe online and don't hesitate to ask if you have more questions. Knowledge is your best defence!" },
            { "Thanks", "Happy to help! Remember — cybersecurity awareness starts with curiosity, and you're already on the right track." },
            { "Goodbye", "Goodbye! Stay vigilant online. Remember to keep your software updated and never click suspicious links. See you next time!" },
            { "Bye", "Take care and stay cyber-safe! Come back anytime you have more questions." },
            { "See you", "See you later! Keep practising good cyber hygiene. Goodbye!" },
            { "You are helpful", "Thank you, that means a lot! My goal is to make cybersecurity easy to understand. Is there anything else you'd like to know?" },
            { "You're helpful", "Thank you! I'm here to make cybersecurity knowledge accessible to everyone. What else can I help you with?" },
            { "You are amazing", "Thank you so much! I just want to help you stay safe online. What cybersecurity topic can I tell you more about?" },
            { "Well done", "Thank you! Now let's make sure your digital life is just as well-protected. Any cybersecurity questions I can help with?" },
        };

        public static readonly Dictionary<string, string> SecurityTips = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Tip1",  "Never share your passwords with anyone, including IT support staff." },
            { "Tip2",  "Lock your screen whenever you step away from your computer." },
            { "Tip3",  "Be cautious of emails with urgent language demanding immediate action." },
            { "Tip4",  "Use a password manager to generate and store strong, unique passwords." },
            { "Tip5",  "Regularly review app permissions on your phone and revoke unused ones." },
            { "Tip6",  "Check if your email has been in a breach at haveibeenpwned.com." },
            { "Tip7",  "Avoid clicking shortened URLs from unknown sources — they may hide malicious links." },
            { "Tip8",  "Enable automatic software updates so you never miss a security patch." },
            { "Tip9",  "Use a different email address for important accounts like banking and work." },
            { "Tip10", "Always log out of accounts when using a shared or public computer." },
            { "Tip11", "Regularly back up your data to an external drive or secure cloud service." },
            { "Tip12", "Think before you post — oversharing on social media helps attackers profile you." },
            { "Tip13", "When in doubt, throw it out — delete suspicious emails without opening attachments." },
            { "Tip14", "Use WPA3 encryption on your home Wi-Fi router if it is supported." },
            { "Tip15", "Never conduct sensitive transactions (banking, shopping) on public Wi-Fi without a VPN." },
            { "Tip16", "Regularly review which apps have access to your social media or Google account." },
            { "Tip17", "Enable full-disk encryption on your laptop to protect data if it is stolen." },
            { "Tip18", "Be sceptical of 'too good to be true' offers online — they are often scams." },
            { "Tip19", "Use an authenticator app (e.g., Google Authenticator) instead of SMS for 2FA when possible." },
            { "Tip20", "Shred physical documents containing personal information before discarding them." },
        };

        // Dictionary: command > description (updated with new POE commands)
        public static readonly Dictionary<string, string> Commands = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Help",    "Show this list of available commands."              },
            { "Topics",  "List all cybersecurity topics you can ask about."  },
            { "Tip",     "Get a security tip."                               },
            { "Quiz",    "Start the cybersecurity quiz."                     },
            { "Tasks",   "Open the Task Manager to manage your tasks."       },
            { "Log",     "Show the activity log of recent actions."          },
            { "History", "View your conversation history."                   },
            { "Clear",   "Clear the conversation history."                   },
            { "Exit",    "Exit the chatbot."                                 },
        };
    }
}